import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

import {texts} from '../texts/texts';

import { getAllfilesMetadata } from "../lib/mdx";

export default function Home({posts,languaje }) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Jose Luis Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>{texts.greetings[languaje]}</h1>
        <h1 className={styles.title}>¡Welcome to JLLB&apos;s blog!</h1>
        <h2>Currently under construction</h2>
        <p>
          In this blog I will be sharing the techy stuff I find on a daily basis working as
          cloud developer, and at the same time I will learn more about web development.
        </p>
        <div className={styles.grid}>
        {posts.map(post => (
            <Link 
            key ={post.slug}
            href={`/${post.slug}`}>
              <a className={styles.card}>
                <h2>{post.tittle}</h2>
                <p>{post.date}</p>
                <p>{post.description}</p>
              </a>
            </Link>
        ))}

        </div>
      </main>

      <footer className={styles.footer}>
          By José Luis López \ joseluislobell@gmail.com
      </footer>
    </div>
  );
}

export async function getStaticProps() {
  const posts = await getAllfilesMetadata();
  return {
    props: {posts},
  };
}
